### ISSUE TITLE
Convert to Unity terrain?

### ISSUE THREAD

**Issue by Zyles** [jongallant/WorldGeneratorFinal#4]
Hey really nice tutorial and project.

I am pretty new to Unity so I wonder what steps would you need to take to convert this into Unity terrain?

Thanks.

**Comment by haywirephoenix** [comment]
Also interested in this!

**Comment by jongallant** [comment]
You can do this by using the Terrain.terrainData.SetHeights(0,0,Data); method.  You can simply pass it the HeightMap.Data array to get started.   You will want to normalize the data before you pass it to this function.

You could do this by adding the following in MapData -- then calling it of course, to normalize it.

`
    public void Normalize()
    {
        for (int x = 0; x < Data.GetLength(0); x++)
        {
            for (int y = 0; y < Data.GetLength(0); y++)
            {
                Data[x,y] = Data[x, y] = (Data[x, y] - Min) / (Max - Min);
            }
        }        
    }`

This should give you a start on how to accomplish this.  
I do not plan on tackling this feature in this project at this point in time, but it can be done with the above method.
