### ISSUE TITLE
Default project does not wrap spheres correctly

### ISSUE THREAD

**Issue by masonwheeler** [jongallant/WorldGeneratorFinal#6]
I downloaded the project to try it out, and when I ran it as-is, with no changes, I got some very strange output.  First off, it always generates extremely wide, world-spanning continents.  But worse than that is that the sphere mapper doesn't actually produce a spherical world; it just wraps a square around the world, leaving a very clear discontinuity line:

![](https://i.imgur.com/YsNmLbp.png)

Also, as seen here, the "hot band" on the temperature map consistently shows up significantly south of the equator.

Is there any way to tweak the settings to fix this?  None of these problems are showing in the sample image on the main page for the project, so I'm not sure what the disconnect is...

**Comment by jongallant** [comment]
Sorry for the delay.  I resolved this in the latest commit.
